
name: Build Node-RED node
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install -g node-red-nodegen node-red-dev
    - run: node-red-nodegen flows.json
    - run: mv examples node-red-contrib-*/
    - run: cd node-red-contrib-*; node-red-dev validate
    - run: echo $GITHUB_REPOSITORY
