name: Publish Node-RED node
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install -g node-red-nodegen node-red-dev
          node-red-nodegen flows.json
          cd node-red-contrib-*/
          cat package.json | jq ".repository.type|=\"git\"|.repository.url|=\"https://github.com/$GITHUB_REPOSITORY.git\"" > tmp; mv tmp package.json
          mv ../examples .
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
